/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {

// By default, Docusaurus generates a sidebar from the docs folder structure
// tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

// But you can create a sidebar manually
/*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

module.exports = {
  gettingStarted: [
    'getting-started/getting-started',
    {
      type: 'category',
      label: 'Getting started',
      items: [
        'getting-started/developers/developers',
        'getting-started/designers/designers',
      ],
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Getting started',
        description: 'Getting started Tallinn Design System',
        slug: '/getting-started/getting-started',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
    },
  ],
  foundations: [
    'foundations/foundations',
    {
      type: 'category',
      label: 'Color',
      items: [
        'foundations/color/color-overview/color-overview',
        'foundations/color/color-tokens/color-tokens',
      ],
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Color',
        description: 'Foundations of Tallinn Design System',
        slug: '/foundations/color',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
    },
    {
      type: 'category',
      label: 'Typography',
      items: [
        'foundations/typography/typography-overview/typography-overview',
        'foundations/typography/typography-usage-guidelines/typography-usage-guidelines',
        'foundations/typography/typography-tokens/typography-tokens',
      ],
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Typography',
        description: 'Typography of Tallinn Design System',
        slug: '/foundations/typography',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
    },
    {
      type: 'category',
      label: 'Spacing',
      items: ['foundations/spacing/spacing-overview/spacing-overview'],
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Spacing',
        description: 'Foundations of Tallinn Design System',
        slug: '/foundations/spacing',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
    },
    {
      type: 'category',
      label: 'Breakpoints',
      items: [
        'foundations/breakpoints/breakpoints-overview/breakpoints-overview',
      ],
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Breakpoints',
        description: 'Foundations of Tallinn Design System',
        slug: '/foundations/breakpoints',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
    },
  ],
  components: [
    'components/components',
    'components/changelog',
    {
      type: 'category',
      label: 'Actions',
      items: [
        'components/actions/button/button',
        'components/actions/link/link',
        'components/actions/chip/chip',
        'components/actions/switch/switch',
      ],
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Actions',
        description: 'Here are the actions you can take with our components!',
        slug: '/components/actions',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
    },
    {
      type: 'category',
      label: 'Forms',
      items: [
        'components/forms/checkbox/checkbox',
        'components/forms/password-input/password-input',
        'components/forms/textarea/textarea',
        'components/forms/radio/radio',
        'components/forms/select/select',
        'components/forms/phone-input/phone-input',
        'components/forms/text-input/text-input',
        'components/forms/date-picker/date-picker',
        'components/forms/date-input/date-input',
      ],
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Forms',
        description: 'Here are forms you can use with our components',
        slug: '/components/forms',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
    },
    {
      type: 'category',
      label: 'Feedback',
      items: [
        'components/feedback/notification/notification',
        'components/feedback/dialog/dialog',
        'components/feedback/tooltip/tooltip',
        'components/feedback/badge/badge',
        'components/feedback/progress-tracker/progress-tracker',
        'components/feedback/popover/popover',
      ],
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Feedback',
        description: 'Feedback components you can use with our components',
        slug: '/components/feedback',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
    },
    {
      type: 'category',
      label: 'Navigation',
      items: [
        'components/navigation/breadcrumbs/breadcrumbs',
        'components/navigation/pagination/pagination',
      ],
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Navigation',
        description:
          'Here are navigation components you can use with our components!',
        slug: '/components/navigation',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
    },
    {
      type: 'category',
      label: 'Presentation',
      items: [
        'components/presentation/accordion/accordion',
        'components/presentation/tabs/tabs',
        'components/presentation/table/table',
        'components/presentation/card/card',
        "components/presentation/step-by-step/step-by-step",
      ],
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Presentation',
        description:
          'Here are presentation components you can use with our components!',
        slug: '/components/presentation',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
    },
  ],
  patterns: [
    'patterns/patterns',
    {
      type: 'category',
      label: 'Forms',
      items: [
        'patterns/forms/principles/principles',
        'patterns/forms/building-a-form/building-a-form',
        'patterns/forms/choosing-the-right-component/choosing-the-right-component',
      ],
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Forms',
        description: 'Patterns of Tallinn Design System',
        slug: '/patterns/forms',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
    },
  ],
};

// export default sidebars;
